"""User-configurable Microsoft Teams alerts on the saw's live status.

Ported from picos' (the Press Monitoring System's) api/alerts.py, which is
itself written in terms of generic "field: value" documents rather than
anything press-specific - only two things are genuinely Granco-specific in
this whole module: get_current_doc() (see its own docstring for why this
one needs to exist at all, unlike picos' single press_data document) and
list_available_tags()'s EXCLUDED_FIELDS list. The trigger/condition schema,
compound-AND evaluation, comparator set, and one-time/recurring mechanics
below are unchanged from picos' version, plus one addition made here first
and worth carrying back: a third "string" condition type (see below).

Each rule posts to a Teams "Incoming Webhook" (or a Workflows app
"Post to a channel when a webhook request is received" flow) URL supplied
when the alert is created - pasted in by whoever owns that Teams channel,
not generated by this app. That URL is a bearer secret (anyone who has it
can post into that channel); like the rest of this API (see this file's
sibling api/app.py's own module docstring on why reads are open here),
create/update/delete go through a real per-person account
(_current_session(), in app.py) rather than being open the way picos' own
alert endpoints are - this project already has real accounts for schedule
edits, so alert rules get the same treatment rather than picos' more
permissive (documented, deliberate-for-that-app) no-auth stance. The
webhook URL itself is still never read back out through the API in full -
see app.py's _serialize_rule, which only ever returns a masked version.

Runs as its own background poller (start_background_alert_poller, hooked
into api/app.py next to the existing ensure_indexes() SQL_PASS gate),
independent of anything else in this API - this file's own poll loop is
the first in-process background thread this codebase has; every other
long-running piece (collector, publisher, plex_sync) is a separate OS
process today (NSSM/Scheduled Tasks), which can't share a poll loop with a
web request process anyway.

Trigger schema - one trigger is a compound (AND-only; multiple independent
triggers on one rule already give OR from the user's perspective, since
any one of them firing sends a message) list of conditions that must ALL
hold, continuously, for sustained_s before it fires:
    {
        "id": "<hex>",
        "conditions": [
            {"field": str, "type": "bool", "equals": bool, "mode": "becomes"|"stays"},
            {"field": str, "type": "numeric", "comparator": "<"|"<="|">"|">="|"=="|"!=", "threshold": number},
            {"field": str, "type": "string", "equals": str},
            ...
        ],
        "sustained_s": number,
        "active": bool,
    }

The "string" type (exact match only, no substring/regex) doesn't exist in
picos' original version - added here because get_current_doc()'s "state"
field ("RUNNING"/"IDLE"/"UNKNOWN") is neither a bool nor a number, and
picos has an analogous unmet need on fields like "Profile" (currently not
even alertable there - it's written as an array, not a scalar, so it
doesn't surface as a tag at all; a string condition type alone wouldn't
fix that specific field without also touching whatever writes it, but it
does the same job here for "state" today). One general condition type
serves both rather than a Granco-specific special case (e.g. synthesizing
one derived boolean per known state value) that wouldn't help Press.

"mode" on a bool condition is display-only ("becomes True" vs "stays
True" read differently but evaluate identically - see describe_condition)
- purely so the wording someone picked while building it survives into
what's actually shown later, without a second code path.

A rule (one webhook, its label/repeat setting, and its triggers) also
carries "repeat": "recurring" (default - stays armed, re-fires each time
a trigger re-trips after clearing) or "one_time" (deleted entirely the
first time any of its triggers fires, per-request).
"""
import json
import operator as _op
import os
import re
import secrets
import threading
import time
import urllib.error
import urllib.request
from datetime import datetime
from zoneinfo import ZoneInfo

from db import get_db

REPEAT_MODES = ("recurring", "one_time")

_COMPARATORS = {
    "<": _op.lt,
    "<=": _op.le,
    ">": _op.gt,
    ">=": _op.ge,
    "==": _op.eq,
    "!=": _op.ne,
}

# This isn't a general-purpose emailer - every alert is meant for
# someone in this org's own Teams tenant, so anything outside this
# domain is almost certainly a typo, not a deliberate destination.
# Matches app.py's ACCOUNT_EMAIL_DOMAIN (that one keeps its own leading
# "@" for direct string-suffix use there; this one doesn't, to match
# picos' validate_recipient_email logic verbatim).
ALLOWED_RECIPIENT_DOMAIN = "uwh.uacj-group.com"

# Symbols alone assume everyone reads math notation fluently - spelling
# each one out alongside it (see describe_condition) means they don't
# have to.
COMPARATOR_PHRASES = {
    "<": "less than",
    "<=": "less than or equal to",
    ">": "greater than",
    ">=": "greater than or equal to",
    "==": "equal to",
    "!=": "not equal to",
}

BOOL_MODES = ("becomes", "stays")

# Duplicated from api/app.py's own PLANT_TZ rather than imported - this
# module is imported BY app.py (for its routes) and app.py starts this
# module's background poller, so importing PLANT_TZ back out of app.py
# would be circular. A one-line constant duplicated with a comment is the
# same tradeoff this codebase already makes elsewhere (e.g. app.py's own
# _shift_name_for duplicating collector/shifts.py's boundaries rather than
# importing across the Render deployment boundary).
PLANT_TZ = ZoneInfo("America/Chicago")

# get_current_doc() only ever meaningfully changes when a new cycle or
# state transition is written (unlike picos' press_data, which is a
# continuously-updated telemetry snapshot) - polling this fast is more
# than enough headroom and just matches picos' own cadence for
# consistency, rather than because this data changes anywhere near that
# often. Kept identical so sustained_s means the same granularity of time
# in both systems' alert rules.
POLL_INTERVAL_S = 2

# Structural/bookkeeping fields, not saw tags - excluded from
# list_available_tags() so they don't turn into useless "equals this
# exact ISO timestamp" or "equals this dedup key" conditions in the
# trigger builder. Everything else surfaces automatically by type; this
# is the one place Granco's shape needs explicit curation that picos
# never needed (press_data doesn't carry equivalent fields as plain
# top-level string keys - its own timestamp field is a datetime object,
# which already falls through every isinstance check below untouched).
EXCLUDED_FIELDS = {"ts", "ts_start", "ts_end", "source_id", "source"}


def plant_now():
    return datetime.now(PLANT_TZ).replace(tzinfo=None)


def comparator_options():
    """[{"value": "<", "label": "less than"}, ...] in a sensible display
    order - for the frontend's condition dropdown, so the symbol/phrase
    pairing is defined once, here, rather than duplicated client-side."""
    return [{"value": symbol, "label": phrase} for symbol, phrase in COMPARATOR_PHRASES.items()]


def bool_mode_options():
    return [
        {"value": "becomes", "label": "becomes"},
        {"value": "stays", "label": "stays"},
    ]


def mask_webhook_url(url):
    """Never return the real secret through the API - just enough of
    the tail to let someone recognize which channel a given alert
    already points to, without exposing something that could be pasted
    elsewhere to post into a real Teams channel."""
    if not url:
        return None
    tail = url[-6:] if len(url) > 6 else url
    return f"...{tail}"


def get_current_doc(db):
    """Synthesizes one 'live status' dict from Granco's two most recent
    event-log documents. Unlike picos' press_data (a single continuously-
    overwritten telemetry document), this codebase has no equivalent -
    cycles and state_events are both append-only logs (see api/db.py's
    ensure_indexes for the full collection list). This mirrors
    /api/status's own two-query latest-of-each pattern (api/app.py)
    rather than inventing a third way to read the same thing.

    Two type-normalizations happen here, at the boundary, so the generic
    classifier in list_available_tags() works without needing to know
    anything saw-specific:
    - is_trim_cut/batch_reload/blade_engaged_confirmed are stored as
      plain SQLite ints (0/1), not real Python bools (see
      collector/detector.py's _emit_cycle: "is_trim_cut": int(is_trim_cut))
      - cast to bool here so they classify as bool tags, not numeric ones.
    - state ("RUNNING"/"IDLE"/"UNKNOWN") is left as a plain string, for
      the "string" condition type to match against directly, rather than
      exploded into synthesized per-value booleans - see the module
      docstring for why one condition type doing this job is preferred
      over a Granco-specific special case."""
    latest_cycle = db.cycles.find_one(sort=[("ts", -1)], projection={"_id": False}) or {}
    latest_state = db.state_events.find_one(sort=[("ts_start", -1)], projection={"_id": False}) or {}

    doc = dict(latest_cycle)
    doc.update(latest_state)  # no field names collide between the two today; state_events wins if that ever changes

    for bool_field in ("is_trim_cut", "batch_reload", "blade_engaged_confirmed"):
        if bool_field in doc:
            doc[bool_field] = bool(doc[bool_field])

    return doc


def list_available_tags(db):
    """Every get_current_doc() field that's a plain bool, number, or
    string (excluding EXCLUDED_FIELDS' bookkeeping fields), since those
    are the only three kinds of condition the trigger builder understands.
    Read from the latest live documents rather than a hardcoded field
    list, so it stays correct if the collector's own tracked fields ever
    change - the same reason picos' version polls press_data instead of
    hardcoding PLC tags. This and get_current_doc() are the only two
    Granco-specific functions in this module - see the module docstring."""
    doc = get_current_doc(db)
    tags = []
    for key, value in doc.items():
        if key in EXCLUDED_FIELDS:
            continue
        if isinstance(value, bool):
            tags.append({"field": key, "type": "bool"})
        elif isinstance(value, (int, float)):
            tags.append({"field": key, "type": "numeric"})
        elif isinstance(value, str):
            tags.append({"field": key, "type": "string"})
    tags.sort(key=lambda t: t["field"])
    return tags


def _pretty_field(field):
    return re.sub(r"\s*\([^)]*\)\s*$", "", field).strip()


def _format_duration(seconds):
    seconds = int(seconds)
    if seconds < 60:
        return f"{seconds}s"
    minutes, sec = divmod(seconds, 60)
    return f"{minutes}m{sec}s" if sec else f"{minutes}m"


def describe_condition(condition):
    pretty = _pretty_field(condition["field"])
    if condition["type"] == "bool":
        word = "stays" if condition.get("mode") == "stays" else "becomes"
        return f"{pretty} {word} {'True' if condition.get('equals', True) else 'False'}"
    if condition["type"] == "string":
        return f'{pretty} is "{condition.get("equals")}"'
    comparator = condition.get("comparator")
    phrase = COMPARATOR_PHRASES.get(comparator, comparator)
    return f"{pretty} {comparator} {condition.get('threshold')} ({phrase})"


def describe_trigger(trigger):
    core = " AND ".join(describe_condition(c) for c in trigger.get("conditions", []))
    sustained_s = trigger.get("sustained_s") or 0
    if sustained_s > 0:
        # Plain ASCII, not "≥" - same reasoning as picos' version: this
        # also goes out verbatim in the Teams message itself, and some
        # consoles can't render it.
        core += f" for >={_format_duration(sustained_s)}"
    return core


def validate_condition(condition):
    if not isinstance(condition, dict):
        return "each condition must be an object"
    field = condition.get("field")
    if not field or not isinstance(field, str):
        return "each condition needs a field"
    ctype = condition.get("type")
    if ctype not in ("bool", "numeric", "string"):
        return "type must be 'bool', 'numeric', or 'string'"
    if ctype == "bool":
        if not isinstance(condition.get("equals"), bool):
            return "a bool condition needs equals: true/false"
        if condition.get("mode") is not None and condition.get("mode") not in BOOL_MODES:
            return f"mode must be one of {BOOL_MODES}"
    elif ctype == "string":
        equals = condition.get("equals")
        if not isinstance(equals, str) or not equals:
            return "a string condition needs a non-empty equals value"
    else:
        if condition.get("comparator") not in _COMPARATORS:
            return f"comparator must be one of {sorted(_COMPARATORS)}"
        threshold = condition.get("threshold")
        if isinstance(threshold, bool) or not isinstance(threshold, (int, float)):
            return "a numeric condition needs a numeric threshold"
    return None


def validate_trigger(trigger):
    if not isinstance(trigger, dict):
        return "each trigger must be an object"
    conditions = trigger.get("conditions")
    if not isinstance(conditions, list) or not conditions:
        return "each trigger needs at least one condition"
    for condition in conditions:
        err = validate_condition(condition)
        if err:
            return err
    sustained_s = trigger.get("sustained_s", 0)
    if isinstance(sustained_s, bool) or not isinstance(sustained_s, (int, float)) or sustained_s < 0:
        return "sustained_s must be a non-negative number"
    return None


def _build_condition(c):
    condition = {"field": c["field"], "type": c["type"]}
    if c["type"] == "bool":
        condition["equals"] = c["equals"]
        condition["mode"] = c.get("mode") if c.get("mode") in BOOL_MODES else "becomes"
    elif c["type"] == "string":
        condition["equals"] = c["equals"]
    else:
        condition["comparator"] = c["comparator"]
        condition["threshold"] = c["threshold"]
    return condition


def describe_draft_trigger(trigger):
    """Validates a not-yet-created trigger and returns its human-readable
    description (see describe_trigger), without persisting anything.
    Exists as a public entry point (rather than app.py reaching into
    _build_condition directly) so a future natural-language alert-setup
    tool can show someone the exact confirmation wording this API would
    give a normal trigger, before they've committed to creating it.
    Returns (description, None) or (None, error_message)."""
    err = validate_trigger(trigger)
    if err:
        return None, err
    built = {
        "conditions": [_build_condition(c) for c in trigger["conditions"]],
        "sustained_s": trigger.get("sustained_s", 0),
    }
    return describe_trigger(built), None


def default_webhook_url():
    """Most people reuse one shared Teams flow (routed by
    recipient_email, see send_teams) for every alert - DEFAULT_TEAMS_
    WEBHOOK_URL, a Render env var on THIS service (same variable name as
    picos uses on its own Render service, but its own separate value -
    these are two independent deploys, so it may point at the same Teams
    channel or a different one depending on what gets configured). Lets
    someone create alerts without pasting that same URL in every single
    time. Still fully overridable per-alert - see build_rule_doc."""
    return os.environ.get("DEFAULT_TEAMS_WEBHOOK_URL") or None


def validate_webhook_url(url):
    if not url or not isinstance(url, str):
        if default_webhook_url():
            return None  # falls back to the configured default - see build_rule_doc
        return "a Teams webhook URL is required (no default is configured)"
    if not url.startswith("https://"):
        return "the webhook URL must start with https://"
    return None


def validate_recipient_email(email):
    """Required - every alert must specify who it's for. Restricted to
    ALLOWED_RECIPIENT_DOMAIN specifically, not just "looks like an
    email": anything else is almost certainly a mistyped address, not a
    deliberate cross-org destination, and the real per-address
    validation happens on Teams/Power Automate's side anyway when it
    tries to resolve the address to a person."""
    if not email or not isinstance(email, str) or email.count("@") != 1:
        return "a recipient email is required"
    local, _, domain = email.partition("@")
    if not local:
        return "recipient_email doesn't look like a valid email address"
    if domain.lower() != ALLOWED_RECIPIENT_DOMAIN:
        return f"recipient_email must end in @{ALLOWED_RECIPIENT_DOMAIN}"
    return None


def build_rule_doc(payload):
    """Validates payload (the POST /api/alerts body) and returns
    (doc, None) or (None, error_message)."""
    if not isinstance(payload, dict):
        return None, "invalid request body"

    webhook_url = payload.get("webhook_url")
    err = validate_webhook_url(webhook_url)
    if err:
        return None, err
    webhook_url = webhook_url or default_webhook_url()

    recipient_email = payload.get("recipient_email")
    err = validate_recipient_email(recipient_email)
    if err:
        return None, err

    triggers_in = payload.get("triggers")
    if not isinstance(triggers_in, list) or not triggers_in:
        return None, "at least one trigger is required"

    triggers = []
    for t in triggers_in:
        err = validate_trigger(t)
        if err:
            return None, err
        triggers.append({
            "id": secrets.token_hex(4),
            "conditions": [_build_condition(c) for c in t["conditions"]],
            "sustained_s": t.get("sustained_s", 0),
            "active": True,
        })

    label = payload.get("label")
    if label is not None and not isinstance(label, str):
        return None, "label must be a string"

    repeat = payload.get("repeat", "recurring")
    if repeat not in REPEAT_MODES:
        return None, f"repeat must be one of {REPEAT_MODES}"

    return {
        "label": (label.strip() or None) if label else None,
        "active": True,
        "repeat": repeat,
        "created_at": plant_now().isoformat(),
        "webhook_url": webhook_url,
        "recipient_email": recipient_email,
        "triggers": triggers,
    }, None


def send_teams(webhook_url, title, message, recipient_email=None, timeout=10):
    """Adaptive Card payload, wrapped in the "attachments" array a
    Workflows-app "Post an Adaptive Card" flow expects to loop over -
    copied from picos' own confirmed-working version verbatim (a classic
    MessageCard payload makes that kind of flow fail immediately, since
    its for-each over attachments finds nothing to iterate).

    One TextBlock per line rather than a single block with embedded
    "\\n"s - Adaptive Cards treat a literal newline inside one
    TextBlock's text as a space, not a line break.

    recipient_email is a top-level sibling of "attachments", not part
    of the card itself - lets ONE shared flow (its "Post card in a chat
    or channel" action's Recipient field bound to
    triggerBody()?['recipient_email']) serve every alert anyone creates,
    routed per-request to whoever it's for, instead of needing a
    separate flow built per person."""
    body = [{"type": "TextBlock", "text": title, "weight": "Bolder", "size": "Medium", "wrap": True}]
    body.extend({"type": "TextBlock", "text": line, "wrap": True} for line in message.split("\n") if line)
    payload = {
        "attachments": [
            {
                "contentType": "application/vnd.microsoft.card.adaptive",
                "content": {
                    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                    "type": "AdaptiveCard",
                    "version": "1.4",
                    "body": body,
                },
            }
        ]
    }
    if recipient_email:
        payload["recipient_email"] = recipient_email
    req = urllib.request.Request(
        webhook_url,
        data=json.dumps(payload).encode("utf-8"),
        method="POST",
        headers={"Content-Type": "application/json"},
    )
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            return True, resp.status, resp.read().decode("utf-8", "replace")
    except urllib.error.HTTPError as exc:
        body = exc.read().decode("utf-8", "replace")
        return False, exc.code, body
    except (urllib.error.URLError, OSError) as exc:
        return False, None, str(exc)


def _send_teams_async(webhook_url, title, message, recipient_email=None):
    # Fire-and-forget on its own thread - a slow/unreachable webhook
    # endpoint must never delay the alert-evaluator loop's own next poll.
    def _run():
        ok, status, body = send_teams(webhook_url, title, message, recipient_email=recipient_email)
        if not ok:
            print(f"[alerts] Teams send failed ({status}): {body[:200]}")

    threading.Thread(target=_run, daemon=True).start()


class AlertEvaluator:
    """Edge-triggered: a trigger fires once when ALL of its conditions
    have been continuously true together for >= sustained_s, then stays
    quiet (no repeat messages while they keep holding) until they clear
    and trip again. A "one_time" rule is deleted outright the moment any
    one of its triggers fires this way, instead of just re-arming.

    Unchanged from picos' version - this class has no Granco-specific
    knowledge at all, it just evaluates whatever get_current_doc()
    hands it."""

    def __init__(self, db):
        self._db = db
        # (rule_id, trigger_id) -> {"since": datetime|None, "fired": bool}
        self._trigger_state = {}

    def _single_condition_met(self, condition, doc):
        value = doc.get(condition["field"])
        if value is None:
            return False
        if condition["type"] == "bool":
            return bool(value) == bool(condition.get("equals", True))
        if condition["type"] == "string":
            return str(value) == condition.get("equals")
        try:
            value = float(value)
        except (TypeError, ValueError):
            return False
        cmp = _COMPARATORS.get(condition.get("comparator"))
        if cmp is None:
            return False
        return cmp(value, float(condition.get("threshold", 0)))

    def _condition_met(self, trigger, doc):
        conditions = trigger.get("conditions") or []
        return bool(conditions) and all(self._single_condition_met(c, doc) for c in conditions)

    def evaluate(self, doc):
        if not doc:
            return
        now = plant_now()
        rules = list(self._db.alert_rules.find({"active": True}))

        live_keys = set()
        for rule in rules:
            if not rule.get("webhook_url"):
                continue  # malformed/pre-migration document - nothing to send to
            rule_id = rule["_id"]
            rule_consumed = False
            for trigger in rule.get("triggers", []):
                if rule_consumed:
                    break
                if not trigger.get("active", True):
                    continue
                key = (rule_id, trigger["id"])
                live_keys.add(key)
                state = self._trigger_state.setdefault(key, {"since": None, "fired": False})

                if not self._condition_met(trigger, doc):
                    state["since"] = None
                    state["fired"] = False
                    continue

                if state["since"] is None:
                    state["since"] = now
                held_s = (now - state["since"]).total_seconds()
                sustained_s = trigger.get("sustained_s") or 0
                if held_s >= sustained_s and not state["fired"]:
                    state["fired"] = True
                    self._fire(rule, trigger, doc)
                    if rule.get("repeat") == "one_time":
                        self._db.alert_rules.delete_one({"_id": rule_id})
                        rule_consumed = True

        # Forget any trigger that's since been deleted/edited away (or
        # whose rule just got consumed above), so a long-running process
        # doesn't leak memory across rule edits.
        for key in set(self._trigger_state) - live_keys:
            del self._trigger_state[key]

    def _fire(self, rule, trigger, doc):
        desc = describe_trigger(trigger)
        values = ", ".join(f"{c['field']}={doc.get(c['field'])}" for c in trigger.get("conditions", []))
        title = rule.get("label") or "Granco Saw Alert"
        message = f"{desc}\n{values}"
        if rule.get("repeat") == "one_time":
            message += "\n(one-time alert - this rule is now retired)"
        print(f"[alerts] firing rule {rule['_id']} / trigger {trigger['id']}: {desc} ({values})")
        _send_teams_async(rule["webhook_url"], title, message, recipient_email=rule.get("recipient_email"))


def run_alert_loop():
    db = get_db()
    evaluator = AlertEvaluator(db)
    print(f"[alerts] polling saw status for alert rules every {POLL_INTERVAL_S}s")
    while True:
        try:
            doc = get_current_doc(db)
            evaluator.evaluate(doc)
        except Exception as exc:
            print(f"[alerts] poll error (will retry): {exc}")
        time.sleep(POLL_INTERVAL_S)


def start_background_alert_poller():
    threading.Thread(target=run_alert_loop, daemon=True, name="alert-evaluator").start()
